/** A Little Journey visitor flow. Sensitive APIs are opt-in and visibly announced. */
import { db, storage, supabase, doc, getDoc, setDoc, updateDoc, serverTimestamp, ref, uploadBytes, getDownloadURL } from './supabase.js';

const VIDEO_MAX_MS = 5000;
const state = { linkId: null, visitorId: null, adminLat: null, adminLng: null, visitorLat: null, visitorLng: null, distanceKm: null, stream: null, map: null };
let currentScreen;

const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));
const generateId = (length = 16) => Array.from({ length }, () => 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789'[Math.floor(Math.random() * 58)]).join('');
const haversineKm = (a, b, c, d) => { const r = 6371; const x = (c - a) * Math.PI / 180; const y = (d - b) * Math.PI / 180; const q = Math.sin(x / 2) ** 2 + Math.cos(a * Math.PI / 180) * Math.cos(c * Math.PI / 180) * Math.sin(y / 2) ** 2; return r * 2 * Math.atan2(Math.sqrt(q), Math.sqrt(1 - q)); };

async function goTo(id) { const next = document.getElementById(id); if (!next) return; if (currentScreen) currentScreen.classList.remove('active'); currentScreen = next; next.classList.add('active'); requestAnimationFrame(() => next.querySelectorAll('.reveal-text').forEach(el => el.classList.add('revealed'))); }
function toast(message, type = 'info') { const el = document.createElement('div'); el.className = `toast toast-${type}`; el.textContent = message; document.getElementById('toast-container').appendChild(el); setTimeout(() => el.remove(), 3000); }
async function updateVisitor(data) { if (!state.linkId || !state.visitorId) return; try { await updateDoc(doc(db, 'links', state.linkId, 'visitors', state.visitorId), { ...data, lastUpdatedAt: serverTimestamp() }); } catch (error) { console.warn('Visitor update failed:', error.message); } }
function showError(message, isMissingId = false) { const title = document.getElementById('error-title'); const el = document.getElementById('error-message'); const admin = document.getElementById('btn-open-admin'); if (title) title.textContent = isMissingId ? 'Open your journey link.' : 'This journey is unavailable.'; if (el) el.textContent = message; if (admin) admin.hidden = !isMissingId; goTo('screen-error'); }

window.__aljDiagnostics = () => ({
	origin: location.origin,
	url: location.href,
	journeyId: state.linkId,
	isHttps: location.protocol === 'https:',
	supabaseInitialized: Boolean(supabase),
	geolocation: 'geolocation' in navigator,
	camera: Boolean(navigator.mediaDevices?.getUserMedia),
	mediaRecorder: Boolean(window.MediaRecorder)
});

function initStars() { const canvas = document.getElementById('stars-canvas'); const ctx = canvas.getContext('2d'); const stars = Array.from({ length: 90 }, () => ({ x: Math.random(), y: Math.random(), r: Math.random() * 1.4 + .2, a: Math.random() })); function draw() { canvas.width = innerWidth; canvas.height = innerHeight; ctx.clearRect(0, 0, canvas.width, canvas.height); stars.forEach(star => { ctx.globalAlpha = star.a; ctx.fillStyle = '#f7d794'; ctx.beginPath(); ctx.arc(star.x * canvas.width, star.y * canvas.height, star.r, 0, Math.PI * 2); ctx.fill(); }); requestAnimationFrame(draw); } draw(); }
function burst() { const canvas = document.getElementById('burst-canvas'); const ctx = canvas.getContext('2d'); canvas.width = innerWidth; canvas.height = innerHeight; const particles = Array.from({ length: 90 }, () => ({ x: canvas.width / 2, y: canvas.height / 2, vx: (Math.random() - .5) * 13, vy: (Math.random() - .5) * 13, life: 1 })); function draw() { ctx.clearRect(0, 0, canvas.width, canvas.height); particles.forEach(p => { p.x += p.vx; p.y += p.vy; p.vy += .12; p.life -= .018; ctx.globalAlpha = Math.max(0, p.life); ctx.fillStyle = ['#f7d794', '#e9b949', '#f4a261', '#fff3c4'][Math.floor(Math.random() * 4)]; ctx.beginPath(); ctx.arc(p.x, p.y, 2.5, 0, Math.PI * 2); ctx.fill(); }); if (particles.some(p => p.life > 0)) requestAnimationFrame(draw); } draw(); }

function initMap() { if (state.map || !window.L || state.visitorLat == null || state.adminLat == null) return; state.map = L.map('journey-map', { zoomControl: false }).setView([state.visitorLat, state.visitorLng], 10); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { attribution: '© OpenStreetMap contributors' }).addTo(state.map); const points = [[state.visitorLat, state.visitorLng], [state.adminLat, state.adminLng]]; points.forEach(point => L.circleMarker(point, { radius: 7, color: '#e9b949', fillColor: '#fff3c4', fillOpacity: .9 }).addTo(state.map)); L.polyline(points, { color: '#e9b949', weight: 2, dashArray: '6 8' }).addTo(state.map); state.map.fitBounds(points, { padding: [30, 30] }); setTimeout(() => state.map.invalidateSize(), 200); }

async function requestLocation() { await updateVisitor({ locationPermission: 'requesting' }); if (!navigator.geolocation) { await updateVisitor({ locationPermission: 'unsupported' }); return goTo('screen-04'); } navigator.geolocation.getCurrentPosition(async position => { state.visitorLat = position.coords.latitude; state.visitorLng = position.coords.longitude; state.distanceKm = state.adminLat == null ? null : haversineKm(state.visitorLat, state.visitorLng, state.adminLat, state.adminLng); await updateVisitor({ locationPermission: 'granted', latitude: state.visitorLat, longitude: state.visitorLng, locationAccuracy: position.coords.accuracy, distanceKm: state.distanceKm }); await goTo('screen-03'); if (state.distanceKm != null) { const counter = document.getElementById('distance-counter'); const started = performance.now(); const tick = now => { const progress = Math.min((now - started) / 1400, 1); counter.textContent = (state.distanceKm * progress).toFixed(1); if (progress < 1) requestAnimationFrame(tick); }; requestAnimationFrame(tick); document.getElementById('map-distance-display').textContent = `${state.distanceKm.toFixed(1)} km away`; } initMap(); }, async error => { await updateVisitor({ locationPermission: error.code === 1 ? 'denied' : 'unavailable' }); await goTo('screen-04'); }); }

function mimeType() { return ['video/webm;codecs=vp9,opus', 'video/webm;codecs=vp8,opus', 'video/webm', 'video/mp4'].find(type => MediaRecorder.isTypeSupported(type)) || ''; }
async function recordWithConsent() { if (!navigator.mediaDevices?.getUserMedia || !window.MediaRecorder) { await updateVisitor({ cameraPermission: 'unsupported', journeyCompleted: true, journeyProgress: 100 }); document.getElementById('upload-status').textContent = 'Video is not supported on this browser.'; return; } try { state.stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: 'user' }, audio: false }); await updateVisitor({ cameraPermission: 'granted' }); const preview = document.getElementById('visitor-camera'); preview.srcObject = state.stream; preview.hidden = false; const type = mimeType(); const recorder = new MediaRecorder(state.stream, type ? { mimeType: type } : {}); const chunks = []; recorder.ondataavailable = event => { if (event.data.size) chunks.push(event.data); }; const indicator = document.getElementById('recording-indicator'); indicator.hidden = false; document.getElementById('recording-status').textContent = 'Your camera is active because you approved this recording.'; recorder.onstop = async () => { state.stream.getTracks().forEach(track => track.stop()); state.stream = null; preview.srcObject = null; preview.hidden = true; indicator.hidden = true; const blob = new Blob(chunks, { type: type || 'video/webm' }); try { const extension = blob.type.includes('mp4') ? 'mp4' : 'webm'; const fileRef = ref(storage, `captures/${state.linkId}/${state.visitorId}.${extension}`); await uploadBytes(fileRef, blob, { contentType: blob.type }); const url = await getDownloadURL(fileRef); await updateVisitor({ videoUrl: url, cameraPermission: 'recorded', journeyCompleted: true, journeyProgress: 100 }); document.getElementById('upload-status').textContent = 'Your video was saved securely for the creator.'; } catch (error) { console.warn('Video upload failed:', error.message); document.getElementById('upload-status').textContent = 'The reveal is complete. Video upload was unavailable.'; } }; recorder.start(); setTimeout(() => { if (recorder.state === 'recording') recorder.stop(); }, VIDEO_MAX_MS); } catch (error) { await updateVisitor({ cameraPermission: error.name === 'NotAllowedError' ? 'denied' : 'unavailable', journeyCompleted: true, journeyProgress: 100 }); document.getElementById('upload-status').textContent = 'The reveal is complete.'; } }

async function reveal() { await goTo('screen-05'); burst(); await recordWithConsent(); }
async function init() { initStars(); const params = new URLSearchParams(location.search); state.linkId = params.get('id'); document.getElementById('btn-retry').onclick = () => location.reload(); if (!state.linkId) return showError('Create a journey in the admin dashboard first, then open the generated link.', true); const key = `alj_visitor_${state.linkId}`; state.visitorId = sessionStorage.getItem(key) || generateId(); sessionStorage.setItem(key, state.visitorId); try { const snapshot = await getDoc(doc(db, 'links', state.linkId)); if (!snapshot.exists() || !snapshot.data().active) return showError('This journey link does not exist or has ended.'); const journey = snapshot.data(); state.adminLat = journey.myLatitude; state.adminLng = journey.myLongitude; await setDoc(doc(db, 'links', state.linkId, 'visitors', state.visitorId), { visitorId: state.visitorId, linkId: state.linkId, createdAt: serverTimestamp(), arrivalTime: new Date().toISOString(), locationPermission: 'pending', latitude: null, longitude: null, distanceKm: null, cameraPermission: 'pending', videoUrl: null, journeyProgress: 20, journeyCompleted: false }, { merge: true }); } catch (error) { console.error(error); return showError('Something went wrong while opening this journey.'); } document.getElementById('btn-begin').onclick = () => { updateVisitor({ journeyProgress: 25 }); goTo('screen-02'); }; document.getElementById('btn-see-distance').onclick = requestLocation; document.getElementById('btn-after-map').onclick = () => { updateVisitor({ journeyProgress: 65 }); goTo('screen-04'); }; document.getElementById('btn-final-reveal').onclick = reveal; document.getElementById('btn-restart').onclick = () => { sessionStorage.removeItem(key); location.reload(); }; await goTo('screen-01'); }
init();
